### ISSUE TITLE
"TypeError: TensorType does not support iteration." error while running train.py

### ISSUE THREAD

**Issue by Nishanksingla** [baidu-research/ba-dls-deepspeech#18] opened 2017-02-17 22:00 UTC
Hi, 

I am training the model with keras 1.2 version and Theano 0.8.2 version and I am getting the following error. 

Can you please help me in solving this error. 

```
/home/msprj_speaker/.local/lib/python2.7/site-packages/Keras-1.2.0-py2.7.egg/keras/engine/topology.py:368: UserWarning: The `regularizers` property of layers/models is deprecated. Regularization losses are now managed via the `losses` layer/model property.
  warnings.warn('The `regularizers` property of '
2017-02-17 13:56:29,979 INFO    (model) Building train_fn
Traceback (most recent call last):
  File "train.py", line 155, in <module>
    args.sortagrad)
  File "train.py", line 126, in main
    train_fn = compile_train_fn(model)
  File "/home/msprj_speaker/ba-dls-deepspeech/model.py", line 51, in compile_train_fn
    updates=updates)
  File "/home/msprj_speaker/.local/lib/python2.7/site-packages/Keras-1.2.0-py2.7.egg/keras/backend/theano_backend.py", line 929, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/msprj_speaker/.local/lib/python2.7/site-packages/Keras-1.2.0-py2.7.egg/keras/backend/theano_backend.py", line 908, in __init__
    for v, nv in updates:
  File "/home/msprj_speaker/.local/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg/theano/tensor/var.py", line 553, in __iter__
    raise TypeError(('TensorType does not support iteration. '
TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)
```

**Comment by srvinay** [comment] 2017-02-20 16:52
Probably a duplicate of #12 . The solution was:
```pip install Keras==1.1.0```

**Closed as completed by srvinay** 2017-02-20 16:52 UTC
